language: node_js
node_js:
  - "10.15.2"
branches:
  only:
    - master
script:
  - echo "Deploying"
before_script:
  - npm i -g firebase-tools

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FKEY

after_success:
  - echo "Deployed"